POST http://localhost:8080/signup
content-type: application/json

{
    "firstName": "Anthony",
    "lastName":  "Bobanza",
    "email": "rza@wutangfinancial.com",
    "password": "shimmyshimmyya"
}

