POST http://localhost:8080/events
content-type: application/json

{
    "Name": "Olympic games",
    "Location": "Somewhere over the mother loving rainboy",
    "Date": "2025-05-13T14:59:27.725943945-05:00",
    "Invitees": 200000
}