POST http://localhost:8080/events
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjIyODk0MzAsImlzcyI6ImFudGhvbnlrdWdlbC5jb20iLCJuYW1lIjoiSmltbXkgTWNDcmlja2V0Iiwic3ViIjoid2FsYXNkeUBib2phbmdsZS5wZGYifQ.0WI6W_8iPezKqhGhVxZCJeg-ISSDhPK6XHuOKdOMxPY

{
    "Name": "The carnival",
    "Description":  "Hella carnies in hurr rn",
    "Location": "Somewhere over the mother loving rainboy",
    "Date": "2025-08-13T14:59:27.725943945-05:00",
    "Invitees": 12000,
    "UserID": 3
}